"""Pydantic request and response schemas for NEREUS."""

from app.schemas.analysis import (
    CurrentsAnalysisResponse,
    DatasetAnalysisSummaryResponse,
    DatasetStatisticsResponse,
    DepthRangeSummary,
    SpatialAnalysisResponse,
    SpatialExtentSummary,
    TemporalAnalysisResponse,
    TemporalRangeSummary,
    VariableStatistics,
)
from app.schemas.array_asset import ArrayAssetBase, ArrayAssetCreate, ArrayAssetRead
from app.schemas.data_delivery import (
    CurrentVectorItem,
    CurrentsDeliveryResponse,
    DownsampleMetadata,
    FrontendDatasetMetadata,
    GridDeliveryResponse,
    ProfileDeliveryResponse,
    SliceDeliveryResponse,
    TimeSeriesDeliveryResponse,
    TimeSeriesPoint,
    TransectDeliveryResponse,
    TransectPoint,
    VariableDiscoveryResponse,
    VariableMetadataItem,
)
from app.schemas.dataset import (
    DatasetBase,
    DatasetCreate,
    DatasetDetailRead,
    DatasetFilterParams,
    DatasetRead,
    DatasetUpdate,
)
from app.schemas.geometry import GeoJSONPoint, GeoJSONPolygon, geometry_to_shape, shape_to_wkb
from app.schemas.health import DatabaseHealthResponse, HealthResponse
from app.schemas.ingestion import (
    DatasetArrayAssetManifest,
    DatasetIngestionRequest,
    DatasetIngestionResponse,
    DatasetVariableManifest,
    InSituBatchIngestionRequest,
    InSituBatchIngestionResponse,
    InSituPointManifest,
    MetadataValidationResult,
    SingleArrayAssetIngestionRequest,
)

from app.schemas.observation import (

    ObservationBase,
    ObservationBulkCreate,
    ObservationCreate,
    ObservationFilterParams,
    ObservationRead,
)
from app.schemas.platform import (
    PlatformBase,
    PlatformCreate,
    PlatformFilterParams,
    PlatformRead,
    PlatformUpdate,
)
from app.schemas.processing_job import (
    ProcessingJobBase,
    ProcessingJobCreate,
    ProcessingJobFilterParams,
    ProcessingJobRead,
    ProcessingJobUpdate,
)
from app.schemas.provenance import ProvenanceBase, ProvenanceCreate, ProvenanceRead
from app.schemas.scientific_processing import (
    DerivedFieldRequest,
    DerivedFieldResponse,
    DimensionMetadata,
    GridSliceRequest,
    GridSliceResponse,
    GridSliceStatistics,
    ScientificAssetInspectionResponse,
    VariableArrayMetadata,
)
from app.schemas.validation_run import (

    ValidationComputeRequest,
    ValidationRunBase,
    ValidationRunCreate,
    ValidationRunFilterParams,
    ValidationRunRead,
)
from app.schemas.variable import VariableBase, VariableCreate, VariableRead, VariableUpdate

__all__ = [
    "ArrayAssetBase",
    "ArrayAssetCreate",
    "ArrayAssetRead",
    "CurrentVectorItem",
    "CurrentsAnalysisResponse",
    "CurrentsDeliveryResponse",
    "DatabaseHealthResponse",
    "DatasetAnalysisSummaryResponse",
    "DatasetArrayAssetManifest",
    "DatasetBase",
    "DatasetCreate",
    "DatasetDetailRead",
    "DatasetFilterParams",
    "DatasetIngestionRequest",
    "DatasetIngestionResponse",
    "DatasetRead",
    "DatasetStatisticsResponse",
    "DatasetUpdate",
    "DatasetVariableManifest",
    "DepthRangeSummary",
    "DerivedFieldRequest",
    "DerivedFieldResponse",
    "DimensionMetadata",
    "DownsampleMetadata",
    "FrontendDatasetMetadata",
    "GeoJSONPoint",
    "GeoJSONPolygon",
    "GridDeliveryResponse",
    "GridSliceRequest",
    "GridSliceResponse",
    "GridSliceStatistics",
    "HealthResponse",
    "InSituBatchIngestionRequest",
    "InSituBatchIngestionResponse",
    "InSituPointManifest",
    "MetadataValidationResult",
    "ObservationBase",
    "ObservationBulkCreate",
    "ObservationCreate",
    "ObservationFilterParams",
    "ObservationRead",
    "PlatformBase",
    "PlatformCreate",
    "PlatformFilterParams",
    "PlatformRead",
    "PlatformUpdate",
    "ProcessingJobBase",
    "ProcessingJobCreate",
    "ProcessingJobFilterParams",
    "ProcessingJobRead",
    "ProcessingJobUpdate",
    "ProfileDeliveryResponse",
    "ProvenanceBase",
    "ProvenanceCreate",
    "ProvenanceRead",
    "ScientificAssetInspectionResponse",
    "SingleArrayAssetIngestionRequest",
    "SliceDeliveryResponse",
    "SpatialAnalysisResponse",
    "SpatialExtentSummary",
    "TemporalAnalysisResponse",
    "TemporalRangeSummary",
    "TimeSeriesDeliveryResponse",
    "TimeSeriesPoint",
    "TransectDeliveryResponse",
    "TransectPoint",
    "ValidationComputeRequest",
    "ValidationRunBase",
    "ValidationRunCreate",
    "ValidationRunFilterParams",
    "ValidationRunRead",
    "VariableArrayMetadata",
    "VariableBase",
    "VariableCreate",
    "VariableDiscoveryResponse",
    "VariableMetadataItem",
    "VariableRead",
    "VariableStatistics",
    "VariableUpdate",
    "geometry_to_shape",
    "shape_to_wkb",
]
